name: release

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          include-v-in-tag: false
